name: "👾 Other"
description: Something that doesn't belong elsewhere.
title: "👾 [Other] - <title>"
labels: [
  "Other"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please describe something
      placeholder: Detailed description of what you wanna share...
    validations:
      required: true
  - type: dropdown
    id: contracts
    attributes:
      label: "Contract Name"
      description: Which contract will be enhanced?
      multiple: true
      options:
        - Core Contract
        - Comm Contract
        - Push Token
    validations:
      required: false